### ISSUE TITLE
Do you have any tutorial yet?

### ISSUE THREAD

**Issue by anhlt** [nicholatian/saturn#9]
This project is promising. Do you have any tutorial or document yet?
I want to learn to develop game on GBA but I don't know how to start yet.

**Comment by nicholatian** [comment]
Hi there!

I haven't been developing this engine since I began work on a bigger game engine project, the [ÔÇô Engine](https://www.arqadium.com/oco/) for Arqadium. Since I do a lot of other things (honestly, almost everything atm) for the company, most of my personal projects have fallen to the wayside in priority.

If you're more bent on the GBA in general than game development, you could give [pret](https://github.com/pret) a look, as they do disassemblies of popular games. They have a lively Discord server [here](https://discord.gg/35egsuR).

If you have any other questions, you're welcome to join and ask us on [our Discord server](https://discord.gg/VbJAsHX), or on [Twitter](https://twitter.com/arqadium). I'll close this for now though. Thanks for your interest 🙂
